# Generated by Django 4.1.3 on 2022-11-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.IntegerField()),
                ("data", models.CharField(max_length=8)),
                ("valor", models.CharField(max_length=10)),
                ("CPF", models.CharField(max_length=11)),
                ("cartao", models.CharField(max_length=12)),
                ("hora", models.CharField(max_length=6)),
                ("dono", models.CharField(max_length=14)),
                ("loja", models.CharField(max_length=19)),
                ("uploaded_file", models.FileField(upload_to="uploaded_file/")),
            ],
        ),
    ]
